name: Publish Docker image for frontend
on:
  push:
    paths: 
      - 'frontend/**'
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  push_to_registry:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
        
      - name: Prepare
        run: echo ::set-env name=IMAGE_NAME::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.owner }}/vobe-tube-frontend:latest
