name: Publish Docker image for frontend
on:
  push:
    paths: 
      - 'frontend/**'
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
defaults:
  run:
    working-directory: frontend
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check folder
        run: ls -al
        
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: vobe-io/vobe-tube/vobe-tube-frontend:latest
